name: Compile Pawn
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pawn Compiler
        uses: pablomstk/pawn-compile-action@master
        with:
          # Модтың жолын және инклудтарды көрсет
          pawn-version: "3.10.10"
          input: "gamemodes/anss.pwn" # ОСЫ ЖЕРГЕ .pwn ФАЙЛЫНЫҢ АТЫН ЖАЗ
          include: "pawno/include"
          output: "gamemodes/anss.amx" 

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-mod
          path: gamemodes/*.amx
